### ISSUE TITLE
Update Design of Newsroom Tools Page

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#116]
- [x] Move the newsletter sign-up to the left sidebar (like on this page: https://mediaengagement.org/research/coronavirus-coverage-in-chicago/)
- [x] Come up with a sleeker design for this page: https://mediaengagement.org/tools/
Can use the quiz tools page redo as inspiration, but feel free to propose new ideas: https://mediaengagement.org/quiz-creator/

**Comment by leoncai1999** [comment]
A pull request has been opened for this redesign here: #131
