### ISSUE TITLE
Research Pages: Citation Brackets

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#120]
To add endnotes to a research page, we currently use brackets at the beginning and end of the citation. However, this causes a problem when we have stats that use brackets. Current workaround is to change all brackets within a citation to parenthesis. Ex: [1. (footnote content)]. Would like to find a fix if possible. 

Example research page: https://mediaengagement.org/research/coronavirus-coverage-in-chicago/

**Comment by SimonXie18** [comment]
On Dashboard, where can the footnotes usage of brackets be switched to the parenthesis? I tried using parenthesis directly for footnotes but didn't work.

**Comment by luukee** [comment]
@SimonXie18 One thing to note with WordPress and brackets "[]", WordPress heavily uses [shortcodes](https://wordpress.com/support/shortcodes/) to add features in its content editor. The shortcode functionality is sure to have some affect on this.
