### ISSUE TITLE
Geolocation Surveillance Roundtable page

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#144]
CME is tasked with creating a page for a propaganda event co-hosted by another organization. We’ll be incorporating their ideas, but making sure it still fits the CME webpage aesthetic. The organization we’re working with made a mockup of the page on their site. Their site is black, but we can look at using a theme that fits our site instead. Joel from the Propaganda team is also working on this and added the info into a word doc you can work from (attached). We’re also looking for an animated background to incorporate (I’m thinking we can use it as a header like on this [page](https://www.theatlantic.com/magazine/archive/2021/04/the-internet-doesnt-have-to-be-awful/618079/)). 
 
One thought: I suggested we don’t use “quotes from experts” since we can’t name the people. Leon, Nicholas, Simon: can you look around and see if you can find examples of interesting ways to incorporate the quotes into the page?

- Videos are located [here](https://utexas.box.com/s/y0oqhu4haljq9thov7p9tj7r35adxgz2)
- Title video is [here](https://utexas.box.com/shared/static/7le76ndwj8iqph9fng0y9yofz4o2ef8k.mp4)
- S.T.O.P. logo [here](https://utexas.box.com/s/2p2gpl40ujt7e8jr9aiwbtozhj2s2p4s)
- Mockups attached (text document that has everything and a screengrab of what they thought it might look like): [Geolocation Roundtable Website Mockup_JC.docx](https://github.com/engagingnewsproject/enp-platform/files/6190674/Geolocation.Roundtable.Website.Mockup_JC.docx)
- Paper that needs to be available for download attached: 
[S.T.O.P Conference Report.pdf](https://github.com/engagingnewsproject/enp-platform/files/6190686/S.T.O.P.Conference.Report.pdf)

![Geolocation Page mockup](https://user-images.githubusercontent.com/63860304/112169708-70f4b880-8bc0-11eb-88c9-1fa76c9d303a.png)

**Comment by luukee** [comment]
@katalinadeaven Hey Kat, sorry for the delay on this. I was able to put together the video grid page for us. 

![cme-video-grid](https://user-images.githubusercontent.com/30611098/112707161-69eed400-8e66-11eb-8567-a45aff432c78.png)

You can check out a short video of me navigating it here: https://streamja.com/QpA19. 
Also a short video of the page on WordPress backend: https://streamja.com/kW4XR
It is also live on the staging site here: https://cmestaging.wpengine.com/understanding-geolocation/

Let me know of any changes you would like to see and I'll have them made. Thanks Kat!

**Comment by katalinadeaven** [comment]
Hi @luukee, video grid looks good, but we need to add the S.T.O.P. logo, the title video, and the quotes section & disclaimer. Mock-up doc linked in first comment on this issue shows what these should be & missing elements are up there as well. Let's also use the white CME logo so it's not in that square (attached). We can get rid of the big newsletter box since it also shows up in the footer. Can we get this done today? 
![CME Logo white](https://user-images.githubusercontent.com/63860304/112869108-659f0280-9082-11eb-85fa-d2d5ca538bb9.png)

**Comment by luukee** [comment]
Layout updated @katalinadeaven! These items have been updated:
- S.T.O.P. logo,
- CME white logo,
- title video, 
- quotes section 
- disclaimer,
- PDF download on "here" text

Check it out and let me know if that works for you: https://cmestaging.wpengine.com/understanding-geolocation/

Thanks!

**Comment by katalinadeaven** [comment]
Hey @luukee looks like there are some display issues, at least on my end.
![Geolocation 1](https://user-images.githubusercontent.com/63860304/113001254-3d70db80-9136-11eb-9279-913f09cc6f8f.png)
![Geolocation 2](https://user-images.githubusercontent.com/63860304/113001408-68f3c600-9136-11eb-8ccc-66ac311327c8.png)

**Comment by luukee** [comment]
Very strange @katalinadeaven. I cleared the staging site cache because your screenshots look way off from what I see:

![cmestaging wpengine com_understanding-geolocation_(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/30611098/113022698-b9205780-9139-11eb-8302-8e8d510ad8a7.png)

Let me know if it still looks off for you. Thanks!
