### ISSUE TITLE
Connective Democracy Page

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#163]
- Updating existing [page](https://mediaengagement.org/connective-democracy-initiative/)
- Word doc with text attached
- Title image attached
- Mockup of page attached
- Numbers below refer to numbers in the attached mockup
- 1 Link to existing blogs (links included in word doc)
- 2 &3 Videos available in [Box](https://utexas.box.com/s/sx85qiy9xueaofj3t86d5n9t0q477pxt). SXSW 2021 is the main video (refer to mockup) and the three question videos go underneath
- 4 Create so that the most recent research from the [Bridging Divides](https://mediaengagement.org/vertical/bridging-divides/research/) page shows up
- 5 Link to [research page](https://mediaengagement.org/vertical/bridging-divides/research/)
![Title Image](https://user-images.githubusercontent.com/63860304/121234507-652ca000-c859-11eb-87d7-8934c78ae49b.png)

![Newsrooms Bridge Divides Mockup for Web](https://user-images.githubusercontent.com/63860304/121234480-5b0aa180-c859-11eb-8968-7aa60b290489.png)

[How Newsrooms Can Help Bridge Divides.docx](https://github.com/engagingnewsproject/enp-platform/files/6618684/How.Newsrooms.Can.Help.Bridge.Divides.docx)

**Comment by luukee** [comment]
@katalinadeaven did we have a due date on this project? Thanks!

**Comment by katalinadeaven** [comment]
@luukee I'd like to get it up as soon as we can, but no hard due date. We'll have another new page project coming up, so I don't want to sit on this one.

**Comment by leoncai1999** [comment]
A pull request for this has been created and merged in: https://github.com/engagingnewsproject/enp-platform/pull/169. Now, these changes will be applied to production

**Comment by katalinadeaven** [comment]
- Main video: https://youtu.be/tihnjzNOELs
- Q1: https://youtu.be/GxZ6GQjjYQI
- Q2: https://youtu.be/zuoAz2iQ8cA
- Q3: https://youtu.be/TIoR1ifEYq8
