### ISSUE TITLE
Civic Signals Page Update

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#178]
- Wider layout
- Large title image
- 3 bottom tiles
- possible color theme

![Civi Signals Mockup](https://user-images.githubusercontent.com/30611098/125830372-8090520f-293f-4653-8f90-29b64c49c1c3.png)

**Comment by katalinadeaven** [comment]
- link to right tile: https://mediaengagement.org/research/social-media-how-platforms-can-do-better/
- link to middle tile: https://mediaengagement.org/research/civic-signals-the-qualities-of-flourishing-digital-spaces/
- link to left tile (unpublished draft): https://mediaengagement.org/research/digital-platform-experiences-during-the-pandemic
- new title image attached
![title image](https://user-images.githubusercontent.com/63860304/125838445-6c219b85-2e4d-4fef-a482-78d901a157d3.png)
