### ISSUE TITLE
Propaganda Alumni section

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#186]
The [propagand](https://mediaengagement.org/team/category/propaganda/)a staff page wants to add an alumni section, similar to what the [MEI page](https://mediaengagement.org/team/vertical/media-ethics/) has. It will ONLY have a name, title, and photo and will not click through to a bio.

**Comment by luukee** [comment]
@katalinadeaven Did you want the Propaganda Staff Alumni section to be the same as the [Media Ethics Staff](https://mediaengagement.org/team/vertical/media-ethics/) Research Scholars drop-downs?
<img width="716" alt="Screen Shot 2021-09-03 at 10 25 11 AM" src="https://user-images.githubusercontent.com/30611098/132044575-7a5574e1-dd61-444e-b84d-2ad382ca1c95.png">

**Comment by katalinadeaven** [comment]
I think that looks good to me!

**Comment by luukee** [comment]
@katalinadeaven and you said just like a list of names right? Not formatted like the other staff members:
![Screen Shot 2021-09-03 at 10 53 26 AM](https://user-images.githubusercontent.com/30611098/132047432-f32333df-86aa-4c3d-9569-6ba07d1901e0.png)
. . . correct? So something like this:
![Screen Shot 2021-09-03 at 10 58 36 AM](https://user-images.githubusercontent.com/30611098/132047987-6a1b7fa6-a3fa-410d-89ec-9cd8218c56b6.png)

**Comment by katalinadeaven** [comment]
That's great for Journalism. For Propaganda, they wanted Photo, Name, & and Title (like the staff displays), but it doesn't click through to a bio.

**Comment by katalinadeaven** [comment]
Yes, please!

**Comment by luukee** [comment]
Good to go!

When the team member has been marked as "Alumni" under the "Team Semester" category 

<img width="1430" alt="Screen Shot 2021-09-03 at 1 39 39 PM" src="https://user-images.githubusercontent.com/30611098/132063309-bb68b871-3423-4531-9ced-18ec6da200ec.png">

. . . they show up in the bottom "Alumni" dropdown for both [Journalism](https://cmedev.wpengine.com/team/vertical/journalism/) & [Propaganda](https://cmedev.wpengine.com/team/vertical/propaganda/):

<img width="1374" alt="Screen Shot 2021-09-03 at 1 45 52 PM" src="https://user-images.githubusercontent.com/30611098/132063731-77cc5f1f-9b06-42f9-a160-80c6205c7a8c.png">


as you can see the [Propaganda "Alumni"](https://cmedev.wpengine.com/team/vertical/propaganda/) staff members have their image, name & title. But without a link to their bio.

[Journalism "alumni"](https://cmedev.wpengine.com/team/vertical/journalism/) show up with just their name:

<img width="1419" alt="Screen Shot 2021-09-03 at 1 48 33 PM" src="https://user-images.githubusercontent.com/30611098/132063931-47a9492d-1e62-44e3-b2aa-52d3984cc1c2.png">

Let me know if that works for you. Thanks Kat!
https://cmedev.wpengine.com/team/vertical/propaganda/

**Comment by katalinadeaven** [comment]
I think this will work!
