### ISSUE TITLE
Board Member Bio Page

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#194]
I'd like to update this page to look like our staff pages (we didn't update it when we did the staff)

- Auto sort alphabetical
- Show photo and title, click through for bio (like staff page)
- https://mediaengagement.org/board/

**Comment by luukee** [comment]
@Keolai how do you think we would get a new "Board" category in WP Admin?

And a little hint on how to get the "Board" filter to show on the staff sidebar. . . you will need to remove two pieces of code from this file: https://github.com/engagingnewsproject/enp-platform/blob/master/wp-content/themes/engage/templates/archive.twig 😁

**Comment by luukee** [comment]
Board is now in the Team section. But "Board" in the Team sidebar needs to be below "Collaborators".

**Comment by luukee** [comment]
Done: https://mediaengagement.org/team/vertical/center-leadership/ @katalinadeaven
