### ISSUE TITLE
Solidarity Reporting Page Updates

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#197]
We need to add tiles to the Solidarity Journalism page. Attached is a mockup and the page links you should need.

- Tile 1: [Solidarity Reporting Guide](https://mediaengagement.org/research/solidarity-reporting-guide/) 
- Tile 2: [A Primer on Empathy and Empathy Fatigue](https://mediaengagement.org/research/a-primer-on-empathy-and-empathy-fatigue) 
- Tile 3: [FAQs](https://mediaengagement.org/research/solidarity-reporting-frequently-asked-questions) 
- Tile 4: [Examples of Solidarity Reporting](https://mediaengagement.org/examples-of-solidarity-reporting/) - I copied and modified our press page for this. I changed the title, but it's still appearing as "Research Press Page." I'll need an assist here. I added the photo I want for the tile as "Featured Image," but I'm not sure that's where you need it.
- Tile 5: A[dditional Resources](https://mediaengagement.org/solidarity-reporting-additional-resources/) - I copied and modified our press page for this. I changed the title, but it's still appearing as "Research Press Page." I'll need an assist here. I added the photo I want for the tile as "Featured Image," but I'm not sure that's where you need it.
- Tile 6: [More from Anita Varma](https://mediaengagement.org/more-from-anita-varma/) I added the photo I want for the tile as "Featured Image," but I'm not sure that's where you need it.

![Solidarity Journalism Mockup psd](https://user-images.githubusercontent.com/63860304/141156609-e3c43369-37f7-4593-8d01-a74504705f8c.png)

**Comment by luukee** [comment]
@NWebb5 I was able to push your Solidarity template changes (custom fields too) to the dev site: https://cmedev.wpengine.com/solidarity-journalism/. Let me know if things look good for you. Thanks Nicholas!
