### ISSUE TITLE
Footer Issue

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#198]
It looks like we have a secondary, bulleted footer that's appearing on many of our pages![footer](https://user-images.githubusercontent.com/63860304/141167699-6212bf2f-6e93-41a5-a72f-dbac96a0af65.png)

**Comment by luukee** [comment]
In Appearance / Widgets the Footer Navigation menu was mistakenly added to the Primary widget block. It has been removed. Good to go!
