### ISSUE TITLE
Press Pages Quick Fix

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#203]
Please change the lines to a lighter gray on the press pages (journalism and propaganda) so the page looks a little less heavy. Screenshot attached.
![Press Pages](https://user-images.githubusercontent.com/63860304/144114482-93a0ab83-91be-4c82-9418-c04a65775ecf.png)

**Comment by Keolai** [comment]
Is this good? 
![Uploading Screenshot from 2021-12-01 13-35-17.png…]()

**Comment by Keolai** [comment]
![Screenshot from 2021-12-01 13-35-17](https://user-images.githubusercontent.com/69029671/144301707-65e420d0-208f-4ba4-b520-c16b82654855.png)

Is this good?

**Comment by katalinadeaven** [comment]
Yes, this looks good
