### ISSUE TITLE
Research and Publications Pages Quick Fix

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#204]
Please move the Title Bar text closer to the vertical line. It currently looks a bit like there's a tab space before the title. This is for Journalism, Propaganda, Platforms, and Bridging Divides research pages as well as Journalism, Propaganda, and Science publications pages. See attached screenshot.

![Research Pages](https://user-images.githubusercontent.com/63860304/144114833-b3bec331-c4d1-4d4a-8d63-e72600ae9d79.png)

**Comment by NWebb5** [comment]
Completed on 1/19/2022
