### ISSUE TITLE
Events pages quick fix

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#206]
Change settings so hyperlinks are underlined. Check formatting settings: bullet lists (indentations) and paragraph spaces are not showing correctly. See attached screenshot. 
![Events Page](https://user-images.githubusercontent.com/63860304/144120790-4c2f16aa-6f55-4065-8a88-28b8f09a8c9d.png)

**Comment by luukee** [comment]
@Keolai Looks like the Events plugin's CSS is overwriting our theme's list styles. Could you let me know how would you go about fixing this?

<img width="1439" alt="Screen Shot 2021-11-30 at 12 22 06 PM" src="https://user-images.githubusercontent.com/30611098/144122410-4ef2c4b4-f58d-492b-9c29-e50e88665dd4.png">
