### ISSUE TITLE
Mobile Usability issues 

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#217]
From Email: 

To the owner of [https://mediaengagement.org/]():
Search Console has identified that your site is affected by 2 Mobile Usability issues:

The following issues were found on your site:

- [Clickable elements too close together]()
- [Content wider than screen]()

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.
https://search.google.com/search-console/mobile-usability?resource_id=https://mediaengagement.org/&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en

**Comment by luukee** [comment]
Validation passed on both 

![Screen Shot 2022-02-09 at 12 23 03 PM](https://user-images.githubusercontent.com/30611098/153283872-00e7a7ae-f0e8-4f7a-bdb4-3be86fca594f.png)
![Screen Shot 2022-02-09 at 12 22 53 PM](https://user-images.githubusercontent.com/30611098/153283876-82a14696-e613-4b3c-af55-422cedb3fbe8.png)
