### ISSUE TITLE
Relinking MEI Site to CME

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#227]
Need to redirect https://mediaethicsinitiative.org/ main site and all linked pages to corresponding CME pages. 

A few outstanding questions from Scott:
o	Concerns about indexed content for current urls (CGI actor example)
o	What if Google sees no content on indexed page?
o	If we want to restore the .org site as independent content and continue updating, can we do that? Is there reversibility/archiving?
o	May need to add events with video listing with titles / populate just MEI on dropdown

**Comment by luukee** [comment]
MEI sitemap: https://mediaethicsinitiative.org/sitemap.xml
MediaEngagement sitemap: https://mediaengagement.org/sitemap_index.xml

- [Redirects and Google Search](https://developers.google.com/search/docs/advanced/crawling/301-redirects)

** A couple of research pages are duplicates:
- https://mediaethicsinitiative.org/2017/09/18/the-ethics-of-green-advertising/
- https://mediaengagement.org/research/the-ethics-of-green-advertising/
- https://mediaethicsinitiative.org/2017/09/18/the-ethics-of-green-advertising-2/
- https://mediaengagement.org/research/the-ethics-of-green-advertising-2/
Potentially non-duplicate pages:
- https://mediaethicsinitiative.org/2017/12/15/the-media-ethics-initiative/

Slightly different content:
- https://mediaethicsinitiative.org/about/welcome/ vs https://mediaengagement.org/media-ethics/

**Comment by luukee** [comment]
Side note. . . wrote a little JS snippet to print the MEI tag URL's to the console:
```
ul = document.querySelector('#the-list');
the_list = ul.querySelectorAll('.level-0');

the_list.forEach((item) => {
    view_url = item.querySelector('.view a').href;
    console.log(view_url);
});
```

- [MEI & MediaEngagement Sitemaps Google Sheet](https://docs.google.com/spreadsheets/d/1La9MH0VgN1tn4p2sKERHCwqTOm7bYbyugQp4ITeXLK0/edit?usp=sharing)
