### ISSUE TITLE
Quiz Tool Updates on GitHub

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#253]
We received the following email. Is this an easy update or is it time-intensive? 

Wondering if the latest changes have been released on Github or elsewhere. This doesn't appear to be too up to date. We're interested in jumping back into featuring quizzes, but prefer code we host ourselves.
 
[https://github.com/engagingnewsproject/engaging-quiz](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fengagingnewsproject%2Fengaging-quiz&data=05%7C01%7C%7Cb590ece57daf45d0888208da64222c27%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637932395187553415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VrSMduIGV6mK3zVwNMNsbNVOOwQVKW3PWRpaxq7U%2BXA%3D&reserved=0)
 
Thanks much, and I hope you're staying cool!

**Comment by luukee** [comment]
The Quiz repo is up to date with the latest changes: https://github.com/engagingnewsproject/engaging-quiz. 

You can send that link over to them now :)
