### ISSUE TITLE
MEI Stats

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#254]
Pull stats for old site (pageviews, downloads, etc.)

**Comment by luukee** [comment]
@katalinadeaven You would just like this data downloaded (like a `.csv` file), correct?

**Comment by katalinadeaven** [comment]
> @katalinadeaven You would just like this data downloaded (like a `.csv` file), correct?

Yes - that should work! As long as the file labels things in a way that allows me to know what stats I'm looking at (I've seen files that are almost useless in this regard).

**Comment by luukee** [comment]
All stats can be found on this Google Sheet: https://docs.google.com/spreadsheets/d/1SY8mL_iwyn5UOiPOr6j8Mh7Hbxs4_zptsdHWyqnA5L0/edit#gid=0

**Comment by katalinadeaven** [comment]
Can we pull Jan 2022 through when we shut down (definitely referrals for this time period).  Sept 1 2021 - through when we took site down.
