### ISSUE TITLE
Add New Team Member

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#256]
Does "Team Designation" box on the right side do anything?

**Comment by julia-elias** [comment]
@katalinadeaven I've looked through the code and I only see the "Member Designation" field group under the "Team Member Detail" box being used. I did notice that under the "Team" tab, the team members are grouped into different categories based on whatever title is selected in the "Team Designation" box, but I think that is the only place that it is being used.

**Comment by luukee** [comment]
![Screen Shot 2022-08-02 at 7 34 43 AM](https://user-images.githubusercontent.com/30611098/182400857-65fee70f-2ccf-4352-b152-ea6e9abf1e91.png)

**Comment by luukee** [comment]
@katalinadeaven @julia-elias 

The Team Designation taxonomy/category is something we can easily hide from the front end as to not confuse editors. The dev site has it removed with the sorting on the front end as Leadership first & all then other members alphabetically.

Check it out: https://cmedev.wpengine.com/team/vertical/science-communication/


![Screen Shot 2022-08-02 at 12 32 31 PM](https://user-images.githubusercontent.com/30611098/182458394-9e638482-cf0d-4002-9204-93fe78517163.png)


![Screen Shot 2022-08-02 at 12 33 51 PM](https://user-images.githubusercontent.com/30611098/182458620-3f54a61e-4721-431e-888c-1e7f3065edf9.png)

Let me know if that works for you, thanks!
