### ISSUE TITLE
Adding Date Line to Research and Quick Reads

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#258]
Our tile pages show the date of publication, but it's not on the actual research or quick read pages. Please add to research and quick read pages (on all verticals) under the featured image. Same info as on the tile page (for example "August 31, 2022")

https://mediaengagement.org/research/polarized-information-ecosystems-and-encrypted-messaging-apps/

**Comment by luukee** [comment]
@katalinadeaven Hey Kat, while updating all the plugins I went ahead and added the date and it's live on the main site.

![Screen Shot 2022-09-12 at 9 31 47 AM](https://user-images.githubusercontent.com/30611098/189707650-78772f02-bbb2-4554-ad26-8013ac3ec9bb.png)

Let me know if that's cool with you. Thanks!

**Comment by NWebb5** [comment]
If it still needs to go under the featured image, I can do that.

**Comment by luukee** [comment]
Go for it! Thanks Nicholas
