### ISSUE TITLE
Staff Page Redesign

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#322]
https://mediaengagement.org/team/vertical/center-leadership/
- Moving all to one page
- No longer divided by verticals
- 6 sections divided by headers: Principal Investigators, Staff, Student Researchers, Research Collaborators, Board, Alumni
- All but alumni will have a photo and title underneath
- Only PIs, Staff, and Board will have click-through bios (can we make optional?)
- Alumni will be a drop-down list (like we use now) and only text (no photo or click-through bio)
- Scott's alumni by semester will become alumni
- Every section will sort alphabetically by last name within the section
- No change to click-through bio pages: https://mediaengagement.org/team/dr-natalie-talia/
- Is there a way to build this ahead of time and for me to sort everyone before we push it live?
- Creative notes: can we add border around photos color #333f48; text for section headers will also be that color

![Staff Page Mockup](https://github.com/user-attachments/assets/b3f92e42-1b09-4658-87c9-1afe81f282f6)

**Comment by katalinadeaven** [comment]
Issues: 
-Research sidebar links to bios that will disappear (we need to unlink research pages from bios)
- White paper landing pages havea team link on the side that links to team pages that will no longer exist:https://mediaengagement.org/vertical/propaganda/research/

**Comment by luukee** [comment]
@EthanL06 Lets mark these off as we go. I already completed the alphabetization (perfect word for the spelling bee) :) 

- [ ] Every section should sort alphabetically by last name within the section
- [ ] Alumni should be Name, Title (no photo or bios) - should also be a drop-down like the alumni sections are currently
- [ ] Staff should also have optional click-through bio
- [ ] Border around photos color #333f48
- [ ] Add more space between the sections (for example more space beween the last photos in the principal investigators section and the Staff title)

> some people that are duplicated and have old bio pages

This is totally a dev site issue. It will be fixed on the production site.

- [ ] Angela Lim is an alumni i believe bc I don't see her on any of the other lists
- [ ] Looks like a lot of people are missing from the student researcher section - please check against the list
- [ ] This one is new, but we can move Matt Lease from Principal Investigators to Research Collaborators

> A bunch of photos are also missing

Same, dev site issue, should be fine on the production site.

@katalinadeaven thanks again for looking over this for us.

**Comment by katalinadeaven** [comment]
For the drop-down - no categories necessary! Just one drop-down for the whole category. The alumni title itself can be a drop-down and then every alumni name goes there alphabetically.

**Comment by luukee** [comment]
Thanks Kat!

@EthanL06 The JS related to the dropdown: assets/js/components/PastInternsDropdown.js. You can use this, alter it or create your own. 

Let me know if you have any questions.
