### ISSUE TITLE
Staff Members - Update Team Categories

### ISSUE THREAD

**Issue by julia-elias** [engagingnewsproject/enp-platform#323]
We need to change the "Team category" for each team member on the staff page so that it matches up with the new Team categories we've created (as seen in photo). 
![image](https://github.com/user-attachments/assets/afce4927-ea86-479f-8d9c-032068d6aee0)

Here is a link to a list of all the Team members and the categories that they should be assigned - https://docs.google.com/document/d/1XV6O2SrD-ZUfr4ND1luAAbUIwXw8Y_TIQTb0oh4YM9E/edit?usp=sharing.

**Updating each Team Member's Category**
1. Sign into the WP Admin dashboard.
2. Navigate to the list of Team members in the dashboard.
![image](https://github.com/user-attachments/assets/2cafa4e6-b13e-4935-b7dc-7d705ea498ba)
3. Search for the team member in the search bar or manually find their page. In this case, we're looking for Lee Anh Kahlor.
![image](https://github.com/user-attachments/assets/cc3611e7-7210-4918-bde9-7a5d5e6a5f2f)

4. Hover over the team member's name, and select the "Quick edit" option on the team member's page.
![image](https://github.com/user-attachments/assets/bb9c052d-be6e-446a-b421-ae978a42e23c)

5. Under the "Team category" option, uncheck the Team member's old category if it doesn't match up with their new Team category. For Lee Anh, she is designated as a Principal Investigator, so we will check that option. 
![image](https://github.com/user-attachments/assets/0003d98a-7b9f-4a63-ac51-295bccd32d21)
6. Select the "update" button, and go view the Staff page to make sure the team member's icon and info is appearing under the correct category.
![image](https://github.com/user-attachments/assets/f79f76e6-c8c2-4f6f-8eb9-fda4686df7dc)
![image](https://github.com/user-attachments/assets/503c07d8-6cae-48bc-95e4-77686ae42835)

**Comment by katalinadeaven** [comment]
Once we have all of this sorted out on the live page let's get rid of the old designations on the WP dashboard end so there's no confusion (we should only need the new "Team Category" check box and not the others like "Team Semster" "Team Designation," etc.

**Comment by luukee** [comment]
An explanation for the devs (@julia-elias, @EthanL06, @Tominium, @DavidLungu) on how we can remove these modules:

1. Go to a staff members WP Admin edit page and see what the name of these modules are. Or any other identifiying attributes. Like for "Team Designation" if you hover over the "Add new category link you will see `team_designation` in the URL. This tells us the taxonomy must be related to "team_designation" so we will search the theme code for that.

    ![Screenshot 2024-09-16 at 1 47 18 PM](https://github.com/user-attachments/assets/35ce7a35-15cf-425f-bdb8-a2512a0ed2a5)

  **"taxonomy" what's that!?**

  - _[WordPress taxonomies](https://wordpress.org/documentation/article/taxonomies/) are systems for grouping and categorizing content, such as posts, using predefined or custom terms (e.g., categories or tags). They help organize content for easier navigation and filtering on a website._

2. Searching the theme code:

  - Shift + Command + P - "team_designation"
  
    ![Screenshot 2024-09-16 at 2 04 23 PM](https://github.com/user-attachments/assets/ad887ec1-7df6-4459-bd03-e2bfeba6619f)

  "register_taxonomy" tells me this is where the taxonomy is set up, so lets check that out.

  > _[`register_taxonomy`](https://developer.wordpress.org/reference/functions/register_taxonomy/) is a WordPress function used to create custom taxonomies, allowing you to group content in ways beyond the default categories and tags. This function can be applied to one or more post types and allows for hierarchical (like categories) or non-hierarchical (like tags) classifications._

3. From reading the `register_taxonomy` docs in the link above I see that `show_ui` might have to do with what we want. So I'll set the `src/Managers/Structures/PostTypes/Team.php` _`registerTeamDesignation`_ function to `false`, refresh the WP Admin staff edit page and I see the "Team designation" module is gone!!

    ![Screenshot 2024-09-16 at 2 19 06 PM](https://github.com/user-attachments/assets/e514acdc-633b-42f0-8c07-41f7b8c4c9d8)

## Main thing to learn

WordPress (coding in general) is all about relationships & refrences. Also, referring to docs are essential. 

Using this knowledge will make you a WordPress professional in no time :)

**Comment by katalinadeaven** [comment]
[like]  Deaven, Katalina reacted to your message:
________________________________

**Comment by luukee** [comment]
@EthanL06 

One issue i found was the Member Display Link ACF not working as it should & I think the ACF related and the template code was overwritten in a git merge. So we will need to bring that back. 
- From the [Google Doc](https://docs.google.com/document/d/1XV6O2SrD-ZUfr4ND1luAAbUIwXw8Y_TIQTb0oh4YM9E/edit?pli=1):
  - ![Screenshot 2024-09-26 at 3 14 38 PM](https://github.com/user-attachments/assets/cecd2a62-50f9-493d-bcc1-c3979051b313)
  - As in, their profile picture and name should be clickable. On click it navigates to their bio page. 

Let me know of any questions you have. Thanks!
