### ISSUE TITLE
WP Admin - Permanently Delete Spam Comments

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#344]
![Screenshot 2024-11-05 at 2 58 54 PM](https://github.com/user-attachments/assets/09dc8aa1-544f-4bdb-aaed-530694f20f7b)

1. Ask Kat about the WP Comments and what she'd like to do with them.
2. Permanently delete any and all spam comments

Why? 3,615 comments can slow down our server. They're just taking up space we could use.

**Comment by luukee** [comment]
@DavidLungu Any progress here?

**Comment by DavidLungu** [comment]
> @DavidLungu Any progress here?

Still making progress on this.

**Comment by DavidLungu** [comment]
@luukee Sorry for the delay. Those spam comments are now taken care of.

**Comment by luukee** [comment]
@DavidLungu Great! Thank you. What did you do?

**Comment by DavidLungu** [comment]
> @DavidLungu Great! Thank you. What did you do?

Just went through the comments and noticed emails and names such as "ufabet" coming in bulk so I filtered and took those out as spam and repeated that. Really, there were no legitimate comments that were pending so they all ended up being deleted.

**Comment by luukee** [comment]
Very good. Thank you for doing that David 👍

**Comment by DavidLungu** [comment]
Should we go ahead and close this issue?

**Comment by luukee** [comment]
Yep! Doing that now. Thanks again 😊
