### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#57]
- [x] Plugins
- [x] Wordpress
- [ ] Get rid of dead pages and buttons that are useless
- [ ] Simon: please monitor Wordpress updates and apply as needed. Ask Luke if you're not sure. 
- [x] Running on old version, affects updates
- [ ] Push WP Update and Plugin Updates to GitHub stable repo

**Comment by luukee** [comment]
@katalinadeaven Wordpress and all Plugins have been updated and pushed to the live site.

**Comment by josh6847** [comment]
Remember to ensure everything looks good on mobile device too.

**Comment by luukee** [comment]
@josh6847 looks good from what I can see. Let me know if you see anything that needs changed.

Thanks!
