### ISSUE TITLE
All Verticals

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#58]
- [x] Fix subcategories under team: under verticals, it shows a list of different categories. We just want it to say "team"
- [x] When go to announcements in each vertical, should only see those for that vertical, not all options
- [x] Launch the press drop-down for verticals
- [x] Launch the publications drop-down for verticals. Here's an example: https://www.climatechangecommunication.org/journal-articles/
- [x] Clicking on researcher names next to a research article just jumps to the bottom of the page

**Comment by katalinadeaven** [comment]
https://mediaengagement.org/vertical/journalism/research/ 

For example, here there's a link to "team" but also a subcategory that says researcher

**Comment by katalinadeaven** [comment]
![ex](https://user-images.githubusercontent.com/63860304/89339742-49b69e80-d664-11ea-8330-96bc299aec23.png)
7
The verticals for some reason show subcategories for team. We just want each vertical to have a team link and they link should go to the team page for that vertical.
