### ISSUE TITLE
MEI

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#60]
Add something to the Media Ethics Staff page like a link to “Past Research Scholars” at the bottom? Ideally, this will lead to a page where I can list the names and year of past MEI interns
@katalinadeaven

**Comment by luukee** [comment]
Tag things case studies (we can do these “digital case studies,” “journalism case studies,” etc if that helps sorting), videos, events (upcoming talks), and announcements (like the meet the scholars posts). Perhaps this would make the sortable case studies page easier (“digital ethics” on mediaengagement.org/vertical/media-ethics/ would then route to all the digital ethics case studies, but not the talks on digital ethics).

**Comment by luukee** [comment]
Change the buttons from Full Report to Case Study (is this customizable by page?)

**Comment by luukee** [comment]
Can we get the web gurus to start working on some sort of button, “Using this for Class?" It would allow to count clicks of that button, and then it might open into a short form popup—name of university, name of class? What do you think?

**Comment by katalinadeaven** [comment]
In regard to first comment: a link to “Past Research Scholars” at the bottom for the MEI staff page. Will link to new page with photos, name, year worked with Scott.

https://mediaengagement.org/team/vertical/media-ethics/

**Comment by katalinadeaven** [comment]
- [ ] Past Research Scholars page: at the bottom of the MEI staff page, add a link that leads to a page with a list (name, year, and headshot) of past MEI interns (Simon was looking into this)

- [ ] “Using this for Class?” button located on each case study/research post under Media Ethics: form popup—name of university, name of class. 

- [ ] Get rid of the videos option in the sidebar (still needs to exist in the dropdown menu or in events)

- [ ] When you choose "Case Studies" from the Media Ethics drop-down, it takes you to a landing page that has all of the side menu categories as blocks. But there are also side menu options for "Case Studies" and "Research" that both lead to a list of all published cases (for Case Studies) or all published cases and videos (for research). Scott wants to get rid of the Case Studies and Research menu options and just leave the Case Studies landing page with the block categories for people to choose from.

**Comment by luukee** [comment]
@katalinadeaven In regards to this bullet:

> * [ ]  When you choose "Case Studies" from the Media Ethics drop-down, it takes you to a landing page that has all of the side menu categories as blocks. But there are also side menu options for "Case Studies" and "Research" that both lead to a list of all published cases (for Case Studies) or all published cases and videos (for research). Scott wants to get rid of the Case Studies and Research menu options and just leave the Case Studies landing page with the block categories for people to choose from.

You mean these links need to be removed?

![case studies](https://i.ibb.co/RhrbFZ5/Screen-Shot-2020-08-19-at-9-36-06-AM.png)

**Comment by katalinadeaven** [comment]
Using this for Class Button done, just needs to be checked by @luukee
