### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#61]
- [x] Newsletter signup on left sidebar under contact us
- [ ] Announcements taggable to general

**Comment by luukee** [comment]
Regarding " Announcements taggable to general" @SimonXie18 

From Kat:

> Right now, when we post an announcement we have to choose if it's Journalism, Media Ethics, Propaganda, or SciComm. Then they also show up in the announcement dropdown in their respective verticals. Right now, if we want the announcement in all verticals, we have to tag all of them, but it shows up as "journalism" when you look on the announcements page. https://mediaengagement.org/announcement/vertical/journalism/  I'd like to make a general announcement category so we can avoid that and still have it show up in the announcements for all verticals.

**Comment by luukee** [comment]
@katalinadeaven @SimonXie18 

Hi Kat, Simon has updated the [Contact Us](https://cmestaging.wpengine.com/about-us/contact-us/) page to show the newsletter signup on the left sidebar. 
Could you please review it for us? Thanks!

**Comment by katalinadeaven** [comment]
Looks good!

**Comment by luukee** [comment]
Great!! I will push it to the live site now.

Thanks Kat!

**Comment by luukee** [comment]
Contact page updated on live site: https://mediaengagement.org/about-us/contact-us/
