### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#63]
- [ ] Make the Newsroom Tools page look sleeker (in the Journalism drop-down menu)
- [ ] Staff page edits
- [x] Make the Quiz Tool page sleeker
- [x] Is there a better way to lay out the board page? Tiles?
- [x] "All Research" Button on home page leads to a mess. Let's get rid of it.
@luukee

**Comment by luukee** [comment]
a new comment on this!

**Comment by luukee** [comment]
Footer (@luukee): 
- newsletter on left footer widget area, about dropdown links in right footer widget area.

**Comment by katalinadeaven** [comment]
Staff page edits
- Add Center Leadership page (needs hierarchy ability)
- Verticals have PIs at the top, then go alphabetically
- Staff page becomes Administrative and Technology (alphabetical)
- Delete technology page
