### ISSUE TITLE
Publications Dropdown

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#65]
Duplicate Sriram's press template files `press.php` & `press-template.php` to create the publications dropdown. WP page: **Test Press Template for Journalism**.
- [ ] Header should be all caps.
- [ ] Check with Kat about formatting preferences.

**Comment by luukee** [comment]
** _from Kat:_
Hi Luke,

Below is the example for the publications drop-down. This is what the Sci-Comm team referenced, but I’m open to improvements. For one, I think it would look cleaner if it’s just a title and an image (no abstract underneath). I also want our images to scale to the same size (most of them will likely be the title page of a paper anyway). In the example, all of the links go to a pdf. We may have some pdfs, but many of our publications will link to an external site

Hi Kat, here’s a link to the [example academic article page.](https://www.climatechangecommunication.org/journal-articles/).

**Comment by luukee** [comment]
> ** _from Kat:_
> Hi Luke,
> 
> Below is the example for the publications drop-down. This is what the Sci-Comm team referenced, but I’m open to improvements. For one, I think it would look cleaner if it’s just a title and an image (no abstract underneath). I also want our images to scale to the same size (most of them will likely be the title page of a paper anyway). In the example, all of the links go to a pdf. We may have some pdfs, but many of our publications will link to an external site
> 
> Hi Kat, here’s a link to the [example academic article page.](https://www.climatechangecommunication.org/journal-articles/).

Agreed Kat! The abstract is too much. 

When you say publications drop-down do you mean the dropdown on the top navigation? But it is basically a separate Publications page altogether? I just want to be 100% clear on it ;)

We can set it up to where you can link to an external page or a PDF.

** it would be super cool if we could have these conversations in GitHub issues so we have an ongoing record of it :) So I added it to the Publications Dropdown Issue(this page!) for us.

Thanks Kat!

**Comment by katalinadeaven** [comment]
Yes, it is a page that we can link, like the press "drop-down." We've just been referring to it as the drop-down since the PI's requested the pages as a menu option.

**Comment by luukee** [comment]
### Keep track of the amount of hours. . .

**Comment by luukee** [comment]
@katalinadeaven Hey Kat, could you send over example links to the publication types you might use? That will be super helpful for me to get the layout looking primo :)

Thanks!

**Comment by katalinadeaven** [comment]
[Peer reviewed pubs Atkinsin_Dudo_Kahlor_17_to_20.docx](https://github.com/engagingnewsproject/enp-platform/files/4914648/Peer.reviewed.pubs.Atkinsin_Dudo_Kahlor_17_to_20.docx)

@luukee Hey Luke, this doc includes links to the publication sites. On our page, we will definitely need the title (they're usually pretty long, which we might want to keep in mind). I was thinking of using the block approach, but not sure what the images would end up being. I don't think we'll have pdfs available for all of these in order to use the cover page. Would have to be a picture of the journal cover, which would mean we have a lot of repetition. Open to suggestions on what you think would look good.

**Comment by luukee** [comment]
@katalinadeaven Thanks for sending!! That helped a ton!

I worked up a sample publications page for you to check out on the staging site:
https://cmestaging.wpengine.com/publications/

Let me know what you think of the layout. Thanks Kat!

**Comment by luukee** [comment]
Initial feedback.

- Add a date.

**Comment by luukee** [comment]
@katalinadeaven Added the date field! 
![date field added](https://i.ibb.co/2qkRj9Y/cme-date-field-added.png)

You can choose it from the calendar dropdown in the page editor:

![date field](https://i.ibb.co/sb69JbF/date-field.png)

**Comment by katalinadeaven** [comment]
Great, thanks!

**Comment by katalinadeaven** [comment]
Hey Luke- I published and added to the menu, but it still looks like this on my computer.

**Comment by katalinadeaven** [comment]
When adding publications, it’s very difficult to slide up and down to change order. I think the number of entries is slowing down the page.

**Comment by luukee** [comment]
@katalinadeaven The best method of reorganizing the publications is to minimize each entry before dragging. This will help the page on rendering [check out this example video](https://streamja.com/y32VO).

Let me know if that makes sense. Thanks Kat!
