### ISSUE TITLE
Slider: redesign

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#66]
Easier to choose stories (by date, Journalism first)

**Comment by luukee** [comment]
added slider redesign bullets (from slider fix issue)

**Comment by luukee** [comment]
All images for the slides should be the same size/ratio.

**Comment by luukee** [comment]
Add blogs to main page (Use in Your Newsroom)

**Comment by luukee** [comment]
x2 Buttons for the slider for editing

**Comment by katalinadeaven** [comment]
![image](https://user-images.githubusercontent.com/63860304/89464085-75ee2000-d735-11ea-9584-66d9c3c81c8e.png)

The slider image is getting cut off at the bottom. The "Read More" button also gets cut off soemtimes.

**Comment by luukee** [comment]
@katalinadeaven Hey Kat, I fixed the slider issue. Check out the staging site: https://cmestaging.wpengine.com/ and let me know if you are still seeing the cropping issue.

Thanks!!

**Comment by katalinadeaven** [comment]
It looks ok to me on staging

**Comment by luukee** [comment]
Great! Is there anything you would like changed with it?

If not, I will push it live. Thanks Kat @katalinadeaven!
