### ISSUE TITLE
Slider: 1st slides

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#77]
@SimonXie18 Hey Simon I wanted to see if you had time to jump on this little edit? . . . 
_Always have research from the journalism vertical appear first in the slider?_

Let me know if that's something you can get into. Thanks!

**Comment by SimonXie18** [comment]
I am going to take a look at it now.

Luke C Hartman <notifications@github.com>于2020年6月23日 周二下午4:12写道：

**Comment by luukee** [comment]
Thanks Simon.
