### ISSUE TITLE
New Research Paper: ability to add people not in CME database.

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#79]
If no CME researchers are related to the paper/post editors need the ability to add non-CME researchers.

**Comment by luukee** [comment]
![Research Additional Members](https://i.ibb.co/vs8jMXq/Screen-Shot-2020-07-20-at-4-27-02-PM.png)

@katalinadeaven Hey Kat, I made the changes for you to easily add additional team members for research projects. You can view the staging [Research Example Page here](https://cmestaging.wpengine.com/research/clone-clickbait-content-may-not-be-click-worthy/).

### For editing check out this video: https://streamja.com/7aWoV

**Comment by luukee** [comment]
- no linking on original team members

**Comment by luukee** [comment]
@katalinadeaven The linking has been removed from the team members sidebar. You can check it on this page: https://mediaengagement.org/research/trust-in-tv-news/

Let me know if you need any more changes. Thanks Kat!
- Luke

**Comment by katalinadeaven** [comment]
Hey Luke, I think we got some wires crossed. I do still want the CME team member names to link to their web bios. What I want to get rid of is links for people who are not CME (so those we add under the "additional team members" section you just worked on. Those people don't have bios on our site, so the links were just jumping to our main staff page (where we wouldn't have them listed anyway).

**Comment by luukee** [comment]
@katalinadeaven Ahh, I see. I thought I had it set up that way initially: 

But it is set up that way now for sure :) 

- CME Team Member = Link
- CME Additional Member = No Link

Let me know if you still need changes on this. Thanks!

**Comment by katalinadeaven** [comment]
Thanks, Luke. The only thing I'm noticing is that the staff lists their name again instead of position. Can we switch that? We also talked about changing it so that the CME team member is not a required field for cases in which we post something written by someone from an outside organization. Thanks!
![ex](https://user-images.githubusercontent.com/63860304/88332127-b42a1f00-ccf3-11ea-8b7b-b9b3f930f9f7.png)

**Comment by luukee** [comment]
@katalinadeaven 
Hey Kat, I fixed the duplicate name issue. And made it so you can add zero CME Team Members and add only Additional Team Members. You can check it out on this page: https://cmestaging.wpengine.com/research/clone-clickbait-content-may-not-be-click-worthy/. If you would like a different default graphic, let me know and I'll create one for you. 

Let me know if you are cool with the changes and I'll push it to the production/live site.

Thanks!

**Comment by katalinadeaven** [comment]
There are branding rules associated with the shield, so I don't want to use it there. I think it looked ok with photos only for staff. What do you think? Just to double-check, instead of the double name, it will now show their CME title, right? I'm also thinking ahead- once someone leaves the team, what will happen to their name on the research page? I just had to go back and add names that disappeared from research because we took them off the staff page. Is there a way to switch someone to the "additional names" format automatically if their name no longer links on staff? I realize this may be a pipe dream, but open to suggestions...

**Comment by josh6847** [comment]
Test

**Comment by josh6847** [comment]
Test 2

**Comment by luukee** [comment]
I will remove the shield, no problemo. And yes, it will show their title. 

You add staff via the WP team page correct?
![Image of team add](https://i.ibb.co/SVKDBWZ/Screen-Shot-2020-08-12-at-9-50-07-AM.png)
. . . and I can work this in.

Thanks Kat!

**Comment by luukee** [comment]
@luukee If a grad(team member) graduates, allow editor to deselect all categories (or something else) to list the team member as an "additional team member" (Name & title only)

**Comment by katalinadeaven** [comment]
Yes, we do add through Team on WP.  This sounds good.

**Comment by luukee** [comment]
@katalinadeaven Hey Kat, I updated the team members to where if you mark them as a "Graduate" in the Team Category. . .

![graduate team member category](https://i.ibb.co/kmLy8mz/cme-graduate-teammember.png)

. . . they will show the same as the Additional team members:

![graduate team member display](https://i.ibb.co/SxZnczB/cme-graduate-display.png)

*this is only pushed to the [staging site](https://cmestaging.wpengine.com/research/journalism-through-theater/) for now. So if you are happy with it I will push it to the live site. 

Thanks!

**Comment by katalinadeaven** [comment]
Can we change the internal menu tag to "Former CME" and have it show as "Researcher" under the name on the page? This will apply to students who move on, former staff, PIs, etc. as people move on.

**Comment by luukee** [comment]
You know it! Working on it now. . .

**Comment by luukee** [comment]
Ok @katalinadeaven the setup is done on the [staging site](https://cmestaging.wpengine.com/research/journalism-through-theater/). Now you change the team members to "Former CME" to list them without an image and labeled as a "Researcher":

![img 01](https://i.ibb.co/Vmnf0dc/Screen-Shot-2020-08-17-at-6-30-46-PM.png)
![img 02](https://i.ibb.co/M53r66S/Screen-Shot-2020-08-17-at-6-31-10-PM.png)

Let me know if that works for you and I'll push it live. Thanks Kat!

**Comment by katalinadeaven** [comment]
Looks good to me!
