### ISSUE TITLE
Decision Tree

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/enp-platform#86]
# [decision-tree repo "issues"](https://github.com/engagingnewsproject/decision-tree/issues/4)
- [Voter Registration Doc](https://docs.google.com/document/d/15p7kYTeTjxFGgjTvV3AprSeAslu-erdT/edit#heading=h.gjdgxs)
- [Decision Tree Feedback doc](https://docs.google.com/document/d/1BhfYSGyJKcp_mbpNiBz9KU-bmtIvFD6blVv6l8WMER0/edit#)
- [Decision Tree Preview](https://tree.mediaengagement.org/preview/tree/how-to-register-to-vote-in-texas)
- [Decision Tree Codepen](https://codepen.io/luukee/pen/MWKPGvK)

Complete any feedback from Gina or Kat.

**Comment by katalinadeaven** [comment]
Gina and team found one typo and want to make some changes to the college student path (they realized it might be confusing). Here's a Google Doc with the new changes. https://docs.google.com/document/d/1zsRj2ZL2CFekmX2JNQHirW12pnjb7SpfVmoYDulteVY/edit

**Comment by luukee** [comment]
Decision Tree Due Diligence 
- Make sure the database is storing the data properly
- How will it be used?
