### ISSUE TITLE
Address storage capacity

### ISSUE THREAD

**Issue by josh6847** [engagingnewsproject/enp-platform#92]

**Comment by luukee** [comment]
Using the Smush plugin to downsize all images across each site (Prod, Dev & Staging). Prod savings so far:
![prod-bulk](https://user-images.githubusercontent.com/30611098/123342784-42f77b00-d505-11eb-8bf9-e213b939cedd.png)

**Comment by luukee** [comment]
Brought the storage down quite a bit:

![Screen Shot 2021-06-28 at 3 55 37 PM](https://user-images.githubusercontent.com/30611098/123713500-6a15bb80-d829-11eb-9067-748c2d8c777e.png)
![Screen Shot 2021-06-28 at 3 59 35 PM](https://user-images.githubusercontent.com/30611098/123713714-da244180-d829-11eb-9da9-fafbb11ea021.png)
Before this we were at 137% over, I believe we can shave off another 2gb from the dev site's database after I flush out the enp-quiz tables.

**Comment by luukee** [comment]
![Screen Shot 2021-09-10 at 7 48 45 AM](https://user-images.githubusercontent.com/30611098/132872863-f8b004fe-52a5-4dac-96f4-8f09d7a30feb.png)
After deleting the quiz entries on the dev and staging site we are now at 88%. That is good to see :)
