### ISSUE TITLE
Twitter Feed not updating on site

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#93]

**Comment by Lay-ton** [comment]
Looked into this a little bit. Seems like it might be a caching issue. The plugin we are using hasn't been updated in a year, nor has it been tested on the lastest 3 WordPress versions. I looked at all the code and backend UI stuff and couldn't find anything that stuck out. Maybe the twitter credentials changed? Or it may be that we need to find a new similar plugin and replace it. I think it's something to discuss in the next meeting.

**Comment by luukee** [comment]
Old twitter feed design look, https://cmestaging.wpengine.com/:
![old twitter feed design](https://i.ibb.co/pX2NPvQ/Screen-Shot-2020-09-28-at-12-13-16-PM.png)
